import type { Metadata } from "next";
import { Syne } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/section/Navbar";
import AnimatedCursor from "react-animated-cursor";

const syne = Syne({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${syne.className} dark`}>
        <AnimatedCursor
          color="255, 255 ,255"
          innerSize={12}
          outerSize={35}
          innerScale={1}
          outerScale={1.7}
          outerAlpha={1}
          outerStyle={{
            mixBlendMode: "exclusion",
          }}
        />
        <header>
          <Navbar />
        </header>
        <main className="">{children}</main>
      </body>
    </html>
  );
}
