import type { Metadata } from "next";
import { Syne } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/section/Navbar";
import AnimatedCursor from "react-animated-cursor";

const syne = Syne({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Aviorsol",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${syne.className} dark`}>
        <div className="md:block hidden">
          <AnimatedCursor
            color="255, 255 ,255"
            innerSize={12}
            outerSize={35}
            innerScale={1}
            outerScale={1.7}
            outerAlpha={1}
            outerStyle={{
              mixBlendMode: "exclusion",
            }}
          />
        </div>
        <header>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
